### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by AlfredPros** [RuolinZheng08/renpy-rhythm#1]
I'm a Windows user and when I launched the game, it always immediately crashes.
The game seems to be missing **_multiarray_umath** module.

Below here is the crash log:
[log.txt](https://github.com/RuolinZheng08/renpy-rhythm/files/6502775/log.txt)

**Comment by RuolinZheng08** [comment]
Thanks for the note!
The cause is that the Python shipped with Ren'Py doesn't have that module.
I've updated the project and moved the affected part into a utility script, which should be run with your own Python instead of Ren'Py's.
Would you mind checking to see if that works for you?

**Comment by AlfredPros** [comment]
Yes. It worked now! Thanks for fixing this bug!
