### ISSUE TITLE
How can I make my own beatmap?

### ISSUE THREAD

**Issue by Hazuki-san** [RuolinZheng08/renpy-rhythm#2]
I'd like to make a beatmap for this, but I'd like to know if I can make a beatmap that is not randomized keys. How can I do that?

Example is like osu!mania charts or something like that

**Comment by RuolinZheng08** [comment]
Does this help? https://github.com/RuolinZheng08/renpy-rhythm#automatic-generation-of-beat-map-files
If it's still not clear I might consider making a YouTube video tutorial on this.

**Comment by Hazuki-san** [comment]
Alright, I think that'll do it! Thanks!
